### PR TITLE
fix(v2): make v2 directory for major version bump

### PR DESCRIPTION
**Pull request by celiawaggoner**
note: i'll refactor the `scripts/` to work for multiple versions to reduce some copy paste in a follow up pr

### CODE REVIEW

**Comment by wendychiang** [comment]
do you mean you will delete `v2/scripts` in the following PR?

**Comment by celiawaggoner** [comment]
@wendychiang yeah, i liked to just keep one set of scripts that works for all versions, so we'd need to refactor the test script to run on the root level and any nested directories maybe by adding a version argument or something

**Comment by wendychiang** [comment]
yeah that makes sense, otherwise we might need to update readme to add another test script

**Comment by celiawaggoner** [comment]
closing to try the approach in https://github.com/godaddy/split-go-serializer/pull/15

**Pull request closed without merging**
